// <auto-generated />
using System;
using Ecommerce.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ecommerce.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20250703213315_update product-photo")]
    partial class updateproductphoto
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ecommerce.Core.Entities.Product.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 7, 4, 0, 33, 13, 261, DateTimeKind.Local).AddTicks(7753),
                            Description = "Electronic items",
                            IsDeleted = false,
                            Name = "Electronics",
                            UpdatedAt = new DateTime(2025, 7, 4, 0, 33, 13, 263, DateTimeKind.Local).AddTicks(7451)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 7, 4, 0, 33, 13, 263, DateTimeKind.Local).AddTicks(8245),
                            Description = "Apparel and garments",
                            IsDeleted = false,
                            Name = "Clothing",
                            UpdatedAt = new DateTime(2025, 7, 4, 0, 33, 13, 263, DateTimeKind.Local).AddTicks(8248)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 7, 4, 0, 33, 13, 263, DateTimeKind.Local).AddTicks(8250),
                            Description = "Various genres of books",
                            IsDeleted = false,
                            Name = "Books",
                            UpdatedAt = new DateTime(2025, 7, 4, 0, 33, 13, 263, DateTimeKind.Local).AddTicks(8251)
                        });
                });

            modelBuilder.Entity("Ecommerce.Core.Entities.Product.Photo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PhotoName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Photos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 7, 4, 0, 33, 13, 264, DateTimeKind.Local).AddTicks(6164),
                            IsDeleted = false,
                            PhotoName = "Laptop",
                            ProductId = 1,
                            UpdatedAt = new DateTime(2025, 7, 4, 0, 33, 13, 264, DateTimeKind.Local).AddTicks(6175)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 7, 4, 0, 33, 13, 264, DateTimeKind.Local).AddTicks(6570),
                            IsDeleted = false,
                            PhotoName = "Mobile",
                            ProductId = 2,
                            UpdatedAt = new DateTime(2025, 7, 4, 0, 33, 13, 264, DateTimeKind.Local).AddTicks(6571)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 7, 4, 0, 33, 13, 264, DateTimeKind.Local).AddTicks(6573),
                            IsDeleted = false,
                            PhotoName = "Tablet",
                            ProductId = 3,
                            UpdatedAt = new DateTime(2025, 7, 4, 0, 33, 13, 264, DateTimeKind.Local).AddTicks(6574)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 7, 4, 0, 33, 13, 264, DateTimeKind.Local).AddTicks(6575),
                            IsDeleted = false,
                            PhotoName = "Headphone",
                            ProductId = 4,
                            UpdatedAt = new DateTime(2025, 7, 4, 0, 33, 13, 264, DateTimeKind.Local).AddTicks(6576)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 7, 4, 0, 33, 13, 264, DateTimeKind.Local).AddTicks(6577),
                            IsDeleted = false,
                            PhotoName = "Smartwatch",
                            ProductId = 5,
                            UpdatedAt = new DateTime(2025, 7, 4, 0, 33, 13, 264, DateTimeKind.Local).AddTicks(6578)
                        });
                });

            modelBuilder.Entity("Ecommerce.Core.Entities.Product.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("NewPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OldPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 7, 4, 0, 33, 13, 265, DateTimeKind.Local).AddTicks(1495),
                            Description = "High performance laptop",
                            IsDeleted = false,
                            Name = "Laptop",
                            NewPrice = 20m,
                            OldPrice = 30m,
                            UpdatedAt = new DateTime(2025, 7, 4, 0, 33, 13, 265, DateTimeKind.Local).AddTicks(1505)
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 7, 4, 0, 33, 13, 265, DateTimeKind.Local).AddTicks(2304),
                            Description = "Latest model smartphone",
                            IsDeleted = false,
                            Name = "Smartphone",
                            NewPrice = 20m,
                            OldPrice = 30m,
                            UpdatedAt = new DateTime(2025, 7, 4, 0, 33, 13, 265, DateTimeKind.Local).AddTicks(2306)
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2025, 7, 4, 0, 33, 13, 265, DateTimeKind.Local).AddTicks(2308),
                            Description = "Comfortable cotton t-shirt",
                            IsDeleted = false,
                            Name = "T-Shirt",
                            NewPrice = 20m,
                            OldPrice = 30m,
                            UpdatedAt = new DateTime(2025, 7, 4, 0, 33, 13, 265, DateTimeKind.Local).AddTicks(2309)
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2025, 7, 4, 0, 33, 13, 265, DateTimeKind.Local).AddTicks(2311),
                            Description = "Stylish denim jeans",
                            IsDeleted = false,
                            Name = "Jeans",
                            NewPrice = 20m,
                            OldPrice = 30m,
                            UpdatedAt = new DateTime(2025, 7, 4, 0, 33, 13, 265, DateTimeKind.Local).AddTicks(2312)
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2025, 7, 4, 0, 33, 13, 265, DateTimeKind.Local).AddTicks(2313),
                            Description = "Engaging fiction novel",
                            IsDeleted = false,
                            Name = "Fiction Book",
                            NewPrice = 20m,
                            OldPrice = 30m,
                            UpdatedAt = new DateTime(2025, 7, 4, 0, 33, 13, 265, DateTimeKind.Local).AddTicks(2314)
                        });
                });

            modelBuilder.Entity("Ecommerce.Core.Entities.Product.Photo", b =>
                {
                    b.HasOne("Ecommerce.Core.Entities.Product.Product", null)
                        .WithMany("Photos")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ecommerce.Core.Entities.Product.Product", b =>
                {
                    b.HasOne("Ecommerce.Core.Entities.Product.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Ecommerce.Core.Entities.Product.Product", b =>
                {
                    b.Navigation("Photos");
                });
#pragma warning restore 612, 618
        }
    }
}
